### ISSUE TITLE
notation & syntax changes

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/dependency-in-refinement-logics#7]
The vector notation for subgoal lists was fine for the simplest tactics & tacticals, but it is too unwieldy for defining something like `THEN` or `THENL`. 

I realized, though, that the lists of subgoals are essentially (non-telescopic) contexts, so we should be able to do something like `J ⊩ τ => Ψ ext e` or even `J ⊩ τ => e ⊣ Ψ` (I kind of like the latter).

The `THEN` tactical could then be really succinctly & cleanly expressed:

```
     J ⊩ τ1 => E ⊣ Φ
  |x Φ(x) ⊩ τ2 => F(x) ⊣ Ψ(x)     (x ∈ |Φ|)
---------------------------------------------------------
    J ⊩ τ1;τ2 => [F(x) / x ∈ |Φ|]E ⊣ ⨁_(x ∈ |Φ|) Ψ(x)
```

@freebroccolo Do you have any thoughts about this? Also, when I realized that subgoals can be thought of as a context for the synthesis, I began to wonder if this was perhaps related to any of the things you've been thinking about lately...

**Comment by freebroccolo** [comment]
Yeah, I like the `J ⊩ τ => e ⊣ Ψ` version also.

Also, I think expressing the rules this way makes sense. I think you're right about the connections. The rule you describe has a bit of a monadic flavor to it and seems similar to some of the encodings I've used for metavariables and substitutions (which can often be understood in terms of coends or left Kan extensions).

**Comment by jonsterling** [comment]
OK, cool. It feels like we're approaching something pretty general, which is always a good sign. I need to take another look at your syntax-via-kan-extensions stuff again, or whatever...

**Comment by freebroccolo** [comment]
I think the recent algebra thing probably generalizes most of what I've done before although I haven't added explicit substitutions to it (yet?). I've been working on making the presheaf machinery explicit in order to better understand some of the stuff the category theorists are talking about. Apparently there's a way (which I don't fully grok yet) to understand the relationship between substitution and (higher) metasubstitution in terms enrichment and the Day convolution, which can serve as a monoidal tensor for presheafs. But I can start writing up some of the details I've already figured out.

**Comment by freebroccolo** [comment]
So [here](https://github.com/freebroccolo/higher-order-algebra/blob/e4be66ff05e5f200da2ae815278a77345b45d2bb/src/Syntax.ml#L96-L124) is a partial OCaml implementation of the algebra/logical-framework thing we were talking about which may be relevant. I haven't added the substitution or metavariable stuff yet but I think it should mostly carry over with some changes.
